on: push
name: Build and Publish Front End Framework Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
        
    - name: List output files
      run: ls -al
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://146.148.59.197:55150//www/ryandevelopment_299/public/
        ftp-username: ryandevelopment
        ftp-password: 24Wve5MwjQAIy4f
        local-dir: .docz/dist/ # This folder is NOT going to upload by default unless you add it to .git-ftp-include:  
        git-ftp-args: --insecure
